// ---------------------------------------------------------------------------
// Landmark model definitions for 3D rendering on the game map
// ---------------------------------------------------------------------------

export interface LandmarkModel {
  /** Unique identifier, used as Mapbox source model key */
  readonly id: string
  /** Path to GLB file (relative to public/) */
  readonly uri: string
  /** Map position as [longitude, latitude] */
  readonly position: [number, number]
  /** Model orientation as [pitch, roll, bearing] in degrees */
  readonly orientation: [number, number, number]
}

/**
 * Warnemuende landmark models.
 *
 * Coordinates match the station locations in `lib/demo/data.ts`.
 * GLB files are generated by `scripts/generate-models.ts`.
 */
export const LANDMARK_MODELS: readonly LandmarkModel[] = [
  {
    id: 'lighthouse',
    uri: '/models/lighthouse.glb',
    position: [12.0858, 54.1814],
    orientation: [0, 0, 0],
  },
  {
    id: 'teepott',
    uri: '/models/teepott.glb',
    position: [12.0858, 54.1817],
    orientation: [0, 0, 0],
  },
] as const
